# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Deep Musings
name: Bhavdeep Sethi
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog for random personal thoughts by Bhavdeep Sethi
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://deepmusings.net" # the base hostname & protocol for your site
twitter_username: BhavdeepSethi
github_username: BhavdeepSethi
include: ["_pages"]

destination: docs/
search: true
search_provider: algolia

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dirt"
#minimal_mistakes_skin: "neon"
#minimal_mistakes_skin: "air"
plugins:
  - jekyll-feed

collections:
  quotes:
    output: true
    permalink: /:collection/:path/

author:
  name: "Bhavdeep Sethi"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "The world forgetting, by the world forgot"
  location: "San Francisco, USA"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bhavdeepsethi"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BhavdeepSethi"
    - label: "Personal"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BhavdeepSethi"
    - label: "Work"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/frec-bhavdeep"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/sethibhavdeep"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/bhavdeep.sethi"
    - label: "Hacker News"
      icon: "fab fa-fw fa-hacker-news"
      url: "https://news.ycombinator.com/user?id=BhavdeepSethi"
    - label: "GoodReads"
      icon: "fab fa-fw fa-goodreads"
      url: "https://goodreads.com/bhavdeepsethi"


# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:day/:title.html

paginate_path: "/page/:num/"
# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: quotes
    values:
      layout: single
      author_profile: true
      share: true
      show_date: false

algolia:
  application_id: C43H5CDF4X
  index_name: personal_blog
  search_only_api_key: 0587aeaf0e491e909b9fcee1cb023784
  powered_by: true

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BhavdeepSethi"

category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-include-cache

compress_html:
  clippings: all
  ignore:
    envs: development
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
