# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Deep Musings
name: Bhavdeep Sethi
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog for random personal thoughts
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://deepmusings.net" # the base hostname & protocol for your site
twitter_username: BhavdeepSethi
github_username: BhavdeepSethi
include: ["_pages"]

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "neon"
#minimal_mistakes_skin: "air"
plugins:
  - jekyll-feed

collections:
  quotes:
    output: true
    permalink: /:collection/:path/

deploy:
  - touch .nojekyll
  - git add -A
  - 'git commit -m "Update site: `date`"'
  - git push origin gh-pages

author:
  name: "Bhavdeep Sethi"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "The world forgetting, by the world forgot"
  location: "San Francisco, USA"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bhavdeepsethi"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BhavdeepSethi"
    - label: "Personal"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BhavdeepSethi"
    - label: "Work"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/frec-bhavdeep"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/sethibhavdeep"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/bhavdeep.sethi"

paginate: 5

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: quotes
    values:
      layout: single
      author_profile: true
      share: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
